### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by rossjones**
Bumps the ruby version to 2.4.1 to match view-data.

### CODE REVIEW

**Comment by rossjones** [comment]
Do we need to re-deploy the docker image?

**Comment by olly** [comment]
I'm not actually sure how any of this works, but it does look like there's a conflict here. It looks as if the docker image is build and pushed in the deploy step (which is run after the tests are run).

**Comment by rossjones** [comment]
I think there may be a CI specific docker image.  Probably not urgent anyway and we can wait for LL.

**Comment by rossjones** [comment]
This is no longer necessary as we're not using docker any more.

**Pull request closed without merging**
